version: 1
type: maven
resolver:
  snapshotRepo: SNAPSHOT_REPO_KEY
  releaseRepo: RELEASE_REPO_KEY
  serverID: Default-Server
deployer:
  snapshotRepo: SNAPSHOT_REPO_KEY
  releaseRepo: RELEASE_REPO_KEY
  serverID: Default-Server