package pt.uminho.ceb.biosystems.mew.mewcore.criticality;

public enum TargetIDStrategy {
	
	IDENTIFY_CRITICAL,
	IDENTIFY_ZEROS,
	IDENTIFY_EQUIVALENCES,
	IDENTIFY_NONGENE_ASSOCIATED,
	IDENTIFY_DRAINS_TRANSPORTS,
	IDENTIFY_PATHWAY_RELATED,
	IDENTIFY_HIGH_CARBON_RELATED,
	IDENTIFY_NO_FLUX_WT,
	IDENTIFY_EXPERIMENTAL;
}
